export function reduce(n,masters=true){while(n>9&&!(masters&&[11,22,33].includes(n)))n=String(n).split('').reduce((a,b)=>a+Number(b),0);return n;}
export function parseBirth(text){if(!/^\d{4}-\d{2}-\d{2}$/.test(text))return null;const [y,m,d]=text.split('-').map(Number),v=new Date(y,m-1,d);return v.getFullYear()===y&&v.getMonth()===m-1&&v.getDate()===d?v:null;}
export function numbers(name,birth,now=new Date()){const b=parseBirth(birth);if(!b)throw Error('Enter a valid birth date.');if(b>now)throw Error('Birth date must be today or earlier.');const chars=name.toUpperCase().replace(/[^A-Z]/g,'').split(''),val=c=>(c.charCodeAt(0)-65)%9+1,sum=a=>a.reduce((t,c)=>t+val(c),0),digits=s=>String(s).replace(/\D/g,'').split('').reduce((a,b)=>a+Number(b),0),py=reduce(b.getMonth()+1+b.getDate()+digits(now.getFullYear())),pm=reduce(py+now.getMonth()+1);return {'Life Path':reduce(digits(birth)),'Birthday Number':reduce(b.getDate()),'Expression / Destiny':reduce(sum(chars)),'Soul Urge':reduce(sum(chars.filter(c=>'AEIOU'.includes(c)))),'Personality':reduce(sum(chars.filter(c=>!'AEIOU'.includes(c)))),'Personal Year':py,'Personal Month':pm,'Personal Day':reduce(pm+now.getDate())};}
export function zodiac(birth){const b=parseBirth(birth);if(!b)return null;const n=(b.getMonth()+1)*100+b.getDate(),cuts=[[120,'Aquarius'],[219,'Pisces'],[321,'Aries'],[420,'Taurus'],[521,'Gemini'],[621,'Cancer'],[723,'Leo'],[823,'Virgo'],[923,'Libra'],[1023,'Scorpio'],[1122,'Sagittarius'],[1222,'Capricorn']];return cuts.filter(([x])=>n>=x).at(-1)?.[1]||'Capricorn';}
export function pick(cards,previous){const pool=cards.filter(c=>c.name!==previous);return (pool.length?pool:cards)[Math.floor(Math.random()*(pool.length||cards.length))];}
export function draw(cards,count,reversals=true){if(count>cards.length)throw Error(`This deck has ${cards.length} cards; this spread needs ${count}.`);const remaining=[...cards],result=[];for(let i=0;i<count;i++){const index=Math.floor(Math.random()*remaining.length);result.push({card:remaining.splice(index,1)[0],reversed:reversals&&Math.random()<.5,revealed:false});}return result;}
export function spreadPoints(name,n){if(name.includes('Horseshoe'))return [[.08,.78],[.20,.51],[.34,.31],[.5,.20],[.66,.31],[.80,.51],[.92,.78]];if(name.includes('Celtic'))return [[.35,.48],[.35,.48],[.35,.78],[.15,.48],[.35,.17],[.56,.48],[.82,.80],[.82,.60],[.82,.38],[.82,.16]];if(name.includes('Wheel')||name.includes('Year Ahead'))return Array.from({length:12},(_,i)=>[.5+.37*Math.cos(-Math.PI/2+i*Math.PI/6),.5+.37*Math.sin(-Math.PI/2+i*Math.PI/6)]).concat(n===13?[[.5,.5]]:[]);if(name.includes('Decision'))return [[.5,.15],[.33,.32],[.22,.53],[.13,.76],[.67,.32],[.78,.53],[.87,.76]];if(n===5)return [[.18,.52],[.82,.52],[.5,.28],[.5,.56],[.5,.82]];if(n===6)return [[.22,.25],[.5,.18],[.78,.25],[.22,.70],[.5,.78],[.78,.70]];if(n===1)return [[.5,.5]];if(n===3)return [[.2,.5],[.5,.5],[.8,.5]];return Array.from({length:n},(_,i)=>[(i%4+.5)/4,(Math.floor(i/4)+.5)/Math.ceil(n/4)]);}
export function grantPass(now=Date.now(),hours=24){return now+hours*3600000;}
export function passActive(expires,now=Date.now()){return Number.isFinite(expires)&&expires>now;}
